# Generated by Django 3.1.5 on 2021-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210108_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=100, verbose_name='Количество очков'),
        ),
    ]
