# Generated by Django 3.1.5 on 2021-01-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=100, verbose_name='Ачивка')),
            ],
            options={
                'verbose_name': 'Ачивка',
                'verbose_name_plural': 'Ачивки',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='families',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100, verbose_name='Названия семьи')),
            ],
            options={
                'verbose_name': 'Названия семьи',
                'verbose_name_plural': 'Названия семей',
            },
        ),
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100, verbose_name='Группа заданий')),
            ],
            options={
                'verbose_name': 'Группа заданий',
                'verbose_name_plural': 'Группы заданий',
            },
        ),
        migrations.CreateModel(
            name='prioriry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioriry_name', models.CharField(max_length=100, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Типы приоритетов',
            },
        ),
        migrations.CreateModel(
            name='score_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Набранные баллы')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Набранные баллы',
                'verbose_name_plural': 'Набранные баллы',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='achievement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.achievements', verbose_name='Достижение'),
        ),
        migrations.AddField(
            model_name='task',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments', verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='task',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.events', verbose_name='Участвует в событии'),
        ),
        migrations.AddField(
            model_name='task',
            name='list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lists', verbose_name='Участвует в списке'),
        ),
        migrations.AddField(
            model_name='task',
            name='prioriry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prioriry', verbose_name='Тип приоритета'),
        ),
        migrations.AddField(
            model_name='users',
            name='family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.families', verbose_name='Семья'),
        ),
    ]
